BEGIN;
DO $$
DECLARE cid uuid; uid uuid; othercid uuid; pid uuid; pid2 uuid; fid uuid; rid uuid; ts timestamptz; ts2 timestamptz; rev integer; link jsonb; token text; result jsonb; failed boolean;
BEGIN
 SELECT id,user_id INTO cid,uid FROM public.clients WHERE user_id IS NOT NULL AND status='active' AND NOT churned LIMIT 1;
 SELECT id INTO othercid FROM public.clients WHERE id<>cid LIMIT 1;
 IF cid IS NULL OR othercid IS NULL THEN RAISE EXCEPTION 'QA requires two existing accounts'; END IF;
 PERFORM set_config('request.jwt.claim.sub','957e2e55-69ed-4e12-bcc0-529ea83380a5',true);
 UPDATE public.client_portal_settings SET can_view_posts=true,can_view_captions=true,can_view_media=true,can_view_comments=true,can_comment=true,can_approve=true,can_request_changes=true,can_view_history=true,visible_statuses=ARRAY['review','changes_requested','approved','scheduled','published'] WHERE client_id=cid;
 INSERT INTO public.posts(client_id,title,caption,status,internal_notes) VALUES(cid,'QA UX review','Original caption','review','PRIVATE_SENTINEL') RETURNING id,updated_at INTO pid,ts;
 INSERT INTO public.posts(client_id,title,caption,status) VALUES(cid,'QA UX second','Second caption','review') RETURNING id,updated_at INTO pid2,ts2;
 SET LOCAL ROLE authenticated;
 link:=public.create_approval_link(pid,7);token:=link->>'token';
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub',uid::text,true);
 SET LOCAL ROLE authenticated;
 IF EXISTS(SELECT 1 FROM public.posts WHERE id=pid) THEN RAISE EXCEPTION 'Raw internal post accessible';END IF;
 IF EXISTS(SELECT 1 FROM public.portal_posts WHERE client_id<>cid) THEN RAISE EXCEPTION 'Cross-account read';END IF;
 IF NOT EXISTS(SELECT 1 FROM public.portal_posts WHERE id=pid AND internal_notes IS NULL AND caption='Original caption') THEN RAISE EXCEPTION 'Safe projection missing';END IF;
 result:=public.get_approval_link_post(token);
 IF result->>'id'<>pid::text OR result::text LIKE '%PRIVATE_SENTINEL%' THEN RAISE EXCEPTION 'Unsafe link';END IF;
 failed:=false;BEGIN PERFORM public.decide_my_account_post(pid,ts,'changes_requested',' ');EXCEPTION WHEN OTHERS THEN failed:=true;END;IF NOT failed THEN RAISE EXCEPTION 'Empty feedback accepted';END IF;
 failed:=false;BEGIN INSERT INTO public.post_comments(post_id,author_id,content,is_internal)VALUES(pid,uid,'Hidden by client',true);EXCEPTION WHEN insufficient_privilege THEN failed:=true;END;IF NOT failed THEN RAISE EXCEPTION 'Client created internal note';END IF;
 INSERT INTO public.post_comments(post_id,author_id,content,is_internal)VALUES(pid,uid,'Shared review comment',false);
 PERFORM public.decide_approval_link(token,ts,'approved',NULL);
 IF NOT EXISTS(SELECT 1 FROM public.portal_posts WHERE id=pid AND status='approved') THEN RAISE EXCEPTION 'Approval not synchronized';END IF;
 result:=public.get_post_review_history(pid);IF jsonb_array_length(result)<>1 OR result->0->>'decision'<>'approved' OR result->0->>'actor_name' IS NULL THEN RAISE EXCEPTION 'Missing review history';END IF;
 PERFORM public.save_account_intake(cid,'briefing','{"goals":"QA goals"}');
 IF NOT EXISTS(SELECT 1 FROM public.client_onboarding_steps WHERE client_id=cid AND step_key='briefing' AND responses->>'goals'='QA goals') THEN RAISE EXCEPTION 'Intake not persisted';END IF;
 failed:=false;BEGIN PERFORM public.save_account_intake(othercid,'briefing','{"goals":"forbidden"}');EXCEPTION WHEN insufficient_privilege THEN failed:=true;END;IF NOT failed THEN RAISE EXCEPTION 'Cross-account intake';END IF;
 INSERT INTO public.client_requests(client_id,kind,title,description)VALUES(cid,'extra','QA extra','QA extra request')RETURNING id INTO rid;
 RESET ROLE;
 PERFORM set_config('request.jwt.claim.sub','957e2e55-69ed-4e12-bcc0-529ea83380a5',true);
 SET LOCAL ROLE authenticated;
 UPDATE public.posts SET caption='Changed caption' WHERE id=pid RETURNING updated_at,content_revision INTO ts,rev;
 IF rev<>2 OR NOT EXISTS(SELECT 1 FROM public.posts WHERE id=pid AND status='review') THEN RAISE EXCEPTION 'Caption failed to invalidate';END IF;
 IF NOT EXISTS(SELECT 1 FROM public.post_approvals WHERE post_id=pid AND decision='pending') THEN RAISE EXCEPTION 'Decision not reset';END IF;
 UPDATE public.client_requests SET quote_scope='One extra video',quote_amount=100 WHERE id=rid RETURNING quote_revision INTO rev;
 RESET ROLE;PERFORM set_config('request.jwt.claim.sub',uid::text,true);SET LOCAL ROLE authenticated;
 failed:=false;BEGIN PERFORM public.get_approval_link_post(token);EXCEPTION WHEN OTHERS THEN failed:=true;END;IF NOT failed THEN RAISE EXCEPTION 'Old revision link still valid';END IF;
 PERFORM public.accept_extra_quote(rid,rev);
 failed:=false;BEGIN PERFORM public.decide_my_account_posts(jsonb_build_array(jsonb_build_object('id',pid,'updated_at',ts),jsonb_build_object('id',pid2,'updated_at',ts2-interval '1 second')));EXCEPTION WHEN OTHERS THEN failed:=true;END;IF NOT failed THEN RAISE EXCEPTION 'Stale batch accepted';END IF;
 IF EXISTS(SELECT 1 FROM public.portal_posts WHERE id IN(pid,pid2) AND status='approved') THEN RAISE EXCEPTION 'Batch not atomic';END IF;
 PERFORM public.decide_my_account_posts(jsonb_build_array(jsonb_build_object('id',pid,'updated_at',ts),jsonb_build_object('id',pid2,'updated_at',ts2)));
 IF (SELECT count(*) FROM public.portal_posts WHERE id IN(pid,pid2) AND status='approved')<>2 THEN RAISE EXCEPTION 'Batch success missing';END IF;
 RESET ROLE;PERFORM set_config('request.jwt.claim.sub','957e2e55-69ed-4e12-bcc0-529ea83380a5',true);SET LOCAL ROLE authenticated;
 INSERT INTO public.post_files(post_id,file_name,storage_path,mime_type)VALUES(pid,'QA.png',pid::text||'/qa.png','image/png') RETURNING id INTO fid;
 IF NOT EXISTS(SELECT 1 FROM public.posts WHERE id=pid AND status='review' AND content_revision=3) THEN RAISE EXCEPTION 'Media did not invalidate';END IF;
 UPDATE public.posts SET extra_request_id=rid WHERE id=pid2;
 UPDATE public.client_requests SET quote_amount=200 WHERE id=rid;
 IF EXISTS(SELECT 1 FROM public.client_requests WHERE id=rid AND accepted_at IS NOT NULL) THEN RAISE EXCEPTION 'Quote change retained acceptance';END IF;
 link:=public.create_approval_link(pid,7);token:=link->>'token';
 UPDATE public.approval_links SET revoked_at=now() WHERE id=(link->>'id')::uuid;
 UPDATE public.client_portal_settings SET can_view_captions=false,can_view_finance=false WHERE client_id=cid;
 RESET ROLE;PERFORM set_config('request.jwt.claim.sub',uid::text,true);SET LOCAL ROLE authenticated;
 failed:=false;BEGIN PERFORM public.get_approval_link_post(token);EXCEPTION WHEN OTHERS THEN failed:=true;END;IF NOT failed THEN RAISE EXCEPTION 'Revoked link accepted';END IF;
 IF EXISTS(SELECT 1 FROM public.portal_posts WHERE id=pid AND caption IS NOT NULL) THEN RAISE EXCEPTION 'Caption permission bypass';END IF;
 result:=public.get_my_account_workspace();
 IF jsonb_array_length(result->'charges')<>0 OR (result->>'can_view_finance')::boolean THEN RAISE EXCEPTION 'Finance permission bypass';END IF;
 RESET ROLE;
END $$;
ROLLBACK;
SELECT 'PASS: account isolation, safe fields, feedback, comments, versioned approval, atomic batch, stale revision, revoked link, media invalidation, onboarding, extra acceptance and financial permission' AS result;
